package cont;

import com.Key;

/**
 * A client which is interested in the login event, should implement
 * this interface and register itself with login provider
 */
@SuppressWarnings("all")
public interface LoginListener {

  /**
   * Method which will be called by the login provider
   *
   * @param key which has been generated by the server on login
   */
  void onLogin(Key key);
}
